name: Android CI & Release

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
      - name: Install dependencies
        run: |
          cd etf_flutter_app
          flutter pub get
      - name: Build Android APK
        run: |
          cd etf_flutter_app
          flutter build apk --release
      - name: Build Android App Bundle (AAB)
        run: |
          cd etf_flutter_app
          flutter build appbundle --release
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-artifacts
          path: |
            etf_flutter_app/build/app/outputs/flutter-apk/app-release.apk
            etf_flutter_app/build/app/outputs/bundle/release/app-release.aab
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: android-build-${{ github.run_id }}
          name: Android build ${{ github.run_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: etf_flutter_app/build/app/outputs/flutter-apk/app-release.apk
          asset_name: app-release.apk
          asset_content_type: application/vnd.android.package-archive
***
